/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs4125.control.ui.gui;

import BookingPackage.*;
import database.MySQLAccess;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alialdobyan
 */
public class FlightBookingMenu extends javax.swing.JFrame {

    /**
     * Creates new form FlightBooking
     */
    public FlightBookingMenu() throws Exception {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() throws Exception {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox_power = new javax.swing.JCheckBox();
        jCheckBox_wifi = new javax.swing.JCheckBox();
        jCheckBox_meal = new javax.swing.JCheckBox();
        jLabel_baggage = new javax.swing.JLabel();
        jComboBox_flightNumber = new javax.swing.JComboBox<>();
        jComboBox_class = new javax.swing.JComboBox<>();
        jComboBox_baggage = new javax.swing.JComboBox<>();
        jButton_cancel = new javax.swing.JButton();
        jButton_book = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(630, 300));

        jLabel1.setText("Flight Number:");

        jLabel2.setText("Class:");

        jCheckBox_power.setText("Power");
        jCheckBox_power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_powerActionPerformed(evt);
            }
        });

        jCheckBox_wifi.setText("Wifi");
        jCheckBox_wifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_wifiActionPerformed(evt);
            }
        });

        jCheckBox_meal.setText("Meal");
        jCheckBox_meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_mealActionPerformed(evt);
            }
        });

        jLabel_baggage.setText("Baggage:");


        getFlightNumber();


        jComboBox_class.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Class", "Business Class", "Economy Class" }));
        jComboBox_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_classActionPerformed(evt);
            }
        });

        jComboBox_baggage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jComboBox_baggage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_baggageActionPerformed(evt);
            }
        });

        jButton_cancel.setText("Cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jButton_book.setText("Book");
        jButton_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel_baggage)
                        .addComponent(jCheckBox_meal)
                        .addComponent(jCheckBox_wifi)
                        .addComponent(jCheckBox_power)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_cancel)
                        .addGap(25, 25, 25)))
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_baggage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_flightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_book)
                        .addGap(12, 12, 12)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox_flightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jCheckBox_power)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_wifi)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_meal)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_baggage)
                    .addComponent(jComboBox_baggage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_cancel)
                    .addComponent(jButton_book))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>

    private void jComboBox_flightNumberActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBox_classActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBox_powerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBox_wifiActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jCheckBox_mealActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jComboBox_baggageActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        UserMenu userMenu = new UserMenu();
        userMenu.setVisible(true);
        this.dispose();
    }

    private void jButton_bookActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        BookingPrice price;

        price = new FlightBooking();
        boolean powerIsChecked = jCheckBox_power.isSelected();
        boolean mealIsChecked = jCheckBox_meal.isSelected();
        boolean wifiIsChecked = jCheckBox_wifi.isSelected();

        if(powerIsChecked){
            price = new Price_power(price);
        }
        if(mealIsChecked){
            price = new Price_meal(price);
        }
        if(wifiIsChecked){
            price = new Price_wifi(price);
        }

        System.out.println(powerIsChecked + " " + mealIsChecked + " " + wifiIsChecked);
        System.out.println(price.cost());
    }
    
    public void getFlightNumber() throws Exception{

        MySQLAccess flightNumber = new MySQLAccess();

        String [] items = flightNumber.getFlightNumber();

        jComboBox_flightNumber.setModel(new javax.swing.DefaultComboBoxModel<>(items));
        jComboBox_flightNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_flightNumberActionPerformed(evt);
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightBookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightBookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightBookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightBookingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FlightBookingMenu().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(FlightBookingMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton_book;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JCheckBox jCheckBox_meal;
    private javax.swing.JCheckBox jCheckBox_power;
    private javax.swing.JCheckBox jCheckBox_wifi;
    private javax.swing.JComboBox<String> jComboBox_baggage;
    private javax.swing.JComboBox<String> jComboBox_class;
    private javax.swing.JComboBox<String> jComboBox_flightNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_baggage;
    // End of variables declaration
}
